package Entities;
// Generated Oct 2, 2016 12:23:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Comment generated by hbm2java
 */
public class Comment  implements java.io.Serializable {


     private Integer idComment;
     private Application application;
     private Customer customer;
     private String comment;
     private Date commentDateAndTime;
     private boolean state;
     private Set<Commenthasreply> commenthasreplies = new HashSet<Commenthasreply>(0);

    public Comment() {
    }

	
    public Comment(Application application, Customer customer, Date commentDateAndTime, boolean state) {
        this.application = application;
        this.customer = customer;
        this.commentDateAndTime = commentDateAndTime;
        this.state = state;
    }
    public Comment(Application application, Customer customer, String comment, Date commentDateAndTime, boolean state, Set<Commenthasreply> commenthasreplies) {
       this.application = application;
       this.customer = customer;
       this.comment = comment;
       this.commentDateAndTime = commentDateAndTime;
       this.state = state;
       this.commenthasreplies = commenthasreplies;
    }
   
    public Integer getIdComment() {
        return this.idComment;
    }
    
    public void setIdComment(Integer idComment) {
        this.idComment = idComment;
    }
    public Application getApplication() {
        return this.application;
    }
    
    public void setApplication(Application application) {
        this.application = application;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Date getCommentDateAndTime() {
        return this.commentDateAndTime;
    }
    
    public void setCommentDateAndTime(Date commentDateAndTime) {
        this.commentDateAndTime = commentDateAndTime;
    }
    public boolean isState() {
        return this.state;
    }
    
    public void setState(boolean state) {
        this.state = state;
    }
    public Set<Commenthasreply> getCommenthasreplies() {
        return this.commenthasreplies;
    }
    
    public void setCommenthasreplies(Set<Commenthasreply> commenthasreplies) {
        this.commenthasreplies = commenthasreplies;
    }




}


