package Entities;
// Generated Oct 22, 2016 1:21:43 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private Integer idCustomer;
     private City city;
     private Emailvarified emailvarified;
     private Gender gender;
     private String customerFname;
     private String customerMname;
     private String customerLname;
     private Date customerRegDateAndTime;
     private String password;
     private String username;
     private boolean state;
     private String address;
     private String customerImage;
     private Set<Coustomercokiesid> coustomercokiesids = new HashSet<Coustomercokiesid>(0);
     private Set<Wishlist> wishlists = new HashSet<Wishlist>(0);
     private Set<Cart> carts = new HashSet<Cart>(0);
     private Set<Comment> comments = new HashSet<Comment>(0);
     private Set<Customerhasapplication> customerhasapplications = new HashSet<Customerhasapplication>(0);

    public Customer() {
    }

	
    public Customer(City city, Gender gender, String customerFname, Date customerRegDateAndTime, String password, String username, boolean state, String address) {
        this.city = city;
        this.gender = gender;
        this.customerFname = customerFname;
        this.customerRegDateAndTime = customerRegDateAndTime;
        this.password = password;
        this.username = username;
        this.state = state;
        this.address = address;
    }
    public Customer(City city, Emailvarified emailvarified, Gender gender, String customerFname, String customerMname, String customerLname, Date customerRegDateAndTime, String password, String username, boolean state, String address, String customerImage, Set<Coustomercokiesid> coustomercokiesids, Set<Wishlist> wishlists, Set<Cart> carts, Set<Comment> comments, Set<Customerhasapplication> customerhasapplications) {
       this.city = city;
       this.emailvarified = emailvarified;
       this.gender = gender;
       this.customerFname = customerFname;
       this.customerMname = customerMname;
       this.customerLname = customerLname;
       this.customerRegDateAndTime = customerRegDateAndTime;
       this.password = password;
       this.username = username;
       this.state = state;
       this.address = address;
       this.customerImage = customerImage;
       this.coustomercokiesids = coustomercokiesids;
       this.wishlists = wishlists;
       this.carts = carts;
       this.comments = comments;
       this.customerhasapplications = customerhasapplications;
    }
   
    public Integer getIdCustomer() {
        return this.idCustomer;
    }
    
    public void setIdCustomer(Integer idCustomer) {
        this.idCustomer = idCustomer;
    }
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }
    public Emailvarified getEmailvarified() {
        return this.emailvarified;
    }
    
    public void setEmailvarified(Emailvarified emailvarified) {
        this.emailvarified = emailvarified;
    }
    public Gender getGender() {
        return this.gender;
    }
    
    public void setGender(Gender gender) {
        this.gender = gender;
    }
    public String getCustomerFname() {
        return this.customerFname;
    }
    
    public void setCustomerFname(String customerFname) {
        this.customerFname = customerFname;
    }
    public String getCustomerMname() {
        return this.customerMname;
    }
    
    public void setCustomerMname(String customerMname) {
        this.customerMname = customerMname;
    }
    public String getCustomerLname() {
        return this.customerLname;
    }
    
    public void setCustomerLname(String customerLname) {
        this.customerLname = customerLname;
    }
    public Date getCustomerRegDateAndTime() {
        return this.customerRegDateAndTime;
    }
    
    public void setCustomerRegDateAndTime(Date customerRegDateAndTime) {
        this.customerRegDateAndTime = customerRegDateAndTime;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public boolean isState() {
        return this.state;
    }
    
    public void setState(boolean state) {
        this.state = state;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCustomerImage() {
        return this.customerImage;
    }
    
    public void setCustomerImage(String customerImage) {
        this.customerImage = customerImage;
    }
    public Set<Coustomercokiesid> getCoustomercokiesids() {
        return this.coustomercokiesids;
    }
    
    public void setCoustomercokiesids(Set<Coustomercokiesid> coustomercokiesids) {
        this.coustomercokiesids = coustomercokiesids;
    }
    public Set<Wishlist> getWishlists() {
        return this.wishlists;
    }
    
    public void setWishlists(Set<Wishlist> wishlists) {
        this.wishlists = wishlists;
    }
    public Set<Cart> getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set<Cart> carts) {
        this.carts = carts;
    }
    public Set<Comment> getComments() {
        return this.comments;
    }
    
    public void setComments(Set<Comment> comments) {
        this.comments = comments;
    }
    public Set<Customerhasapplication> getCustomerhasapplications() {
        return this.customerhasapplications;
    }
    
    public void setCustomerhasapplications(Set<Customerhasapplication> customerhasapplications) {
        this.customerhasapplications = customerhasapplications;
    }




}


