package Entities;
// Generated Oct 2, 2016 12:23:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Gender generated by hbm2java
 */
public class Gender  implements java.io.Serializable {


     private int idgender;
     private String gender;
     private Set<Customer> customers = new HashSet<Customer>(0);
     private Set<Staff> staffs = new HashSet<Staff>(0);
     private Set<Developer> developers = new HashSet<Developer>(0);

    public Gender() {
    }

	
    public Gender(int idgender, String gender) {
        this.idgender = idgender;
        this.gender = gender;
    }
    public Gender(int idgender, String gender, Set<Customer> customers, Set<Staff> staffs, Set<Developer> developers) {
       this.idgender = idgender;
       this.gender = gender;
       this.customers = customers;
       this.staffs = staffs;
       this.developers = developers;
    }
   
    public int getIdgender() {
        return this.idgender;
    }
    
    public void setIdgender(int idgender) {
        this.idgender = idgender;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Set<Customer> getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set<Customer> customers) {
        this.customers = customers;
    }
    public Set<Staff> getStaffs() {
        return this.staffs;
    }
    
    public void setStaffs(Set<Staff> staffs) {
        this.staffs = staffs;
    }
    public Set<Developer> getDevelopers() {
        return this.developers;
    }
    
    public void setDevelopers(Set<Developer> developers) {
        this.developers = developers;
    }




}


