package Entities;
// Generated Oct 22, 2016 1:21:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private Integer idroles;
     private String roles;
     private boolean state;
     private Set<Staff> staffs = new HashSet<Staff>(0);
     private Set<Rolehassubmenu> rolehassubmenus = new HashSet<Rolehassubmenu>(0);

    public Roles() {
    }

	
    public Roles(String roles, boolean state) {
        this.roles = roles;
        this.state = state;
    }
    public Roles(String roles, boolean state, Set<Staff> staffs, Set<Rolehassubmenu> rolehassubmenus) {
       this.roles = roles;
       this.state = state;
       this.staffs = staffs;
       this.rolehassubmenus = rolehassubmenus;
    }
   
    public Integer getIdroles() {
        return this.idroles;
    }
    
    public void setIdroles(Integer idroles) {
        this.idroles = idroles;
    }
    public String getRoles() {
        return this.roles;
    }
    
    public void setRoles(String roles) {
        this.roles = roles;
    }
    public boolean isState() {
        return this.state;
    }
    
    public void setState(boolean state) {
        this.state = state;
    }
    public Set<Staff> getStaffs() {
        return this.staffs;
    }
    
    public void setStaffs(Set<Staff> staffs) {
        this.staffs = staffs;
    }
    public Set<Rolehassubmenu> getRolehassubmenus() {
        return this.rolehassubmenus;
    }
    
    public void setRolehassubmenus(Set<Rolehassubmenu> rolehassubmenus) {
        this.rolehassubmenus = rolehassubmenus;
    }




}


