package Entities;
// Generated Oct 2, 2016 12:23:07 PM by Hibernate Tools 4.3.1



/**
 * RolehassubmenuId generated by hbm2java
 */
public class RolehassubmenuId  implements java.io.Serializable {


     private int rolesIdroles;
     private int submenuIdsubmenu;

    public RolehassubmenuId() {
    }

    public RolehassubmenuId(int rolesIdroles, int submenuIdsubmenu) {
       this.rolesIdroles = rolesIdroles;
       this.submenuIdsubmenu = submenuIdsubmenu;
    }
   
    public int getRolesIdroles() {
        return this.rolesIdroles;
    }
    
    public void setRolesIdroles(int rolesIdroles) {
        this.rolesIdroles = rolesIdroles;
    }
    public int getSubmenuIdsubmenu() {
        return this.submenuIdsubmenu;
    }
    
    public void setSubmenuIdsubmenu(int submenuIdsubmenu) {
        this.submenuIdsubmenu = submenuIdsubmenu;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RolehassubmenuId) ) return false;
		 RolehassubmenuId castOther = ( RolehassubmenuId ) other; 
         
		 return (this.getRolesIdroles()==castOther.getRolesIdroles())
 && (this.getSubmenuIdsubmenu()==castOther.getSubmenuIdsubmenu());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getRolesIdroles();
         result = 37 * result + this.getSubmenuIdsubmenu();
         return result;
   }   


}


