package Entities;
// Generated Oct 19, 2016 3:46:26 PM by Hibernate Tools 4.3.1



/**
 * Rolehassubmenu generated by hbm2java
 */
public class Rolehassubmenu  implements java.io.Serializable {


     private RolehassubmenuId id;
     private Roles roles;
     private Submenu submenu;
     private Boolean state;

    public Rolehassubmenu() {
    }

	
    public Rolehassubmenu(RolehassubmenuId id, Roles roles, Submenu submenu) {
        this.id = id;
        this.roles = roles;
        this.submenu = submenu;
    }
    public Rolehassubmenu(RolehassubmenuId id, Roles roles, Submenu submenu, Boolean state) {
       this.id = id;
       this.roles = roles;
       this.submenu = submenu;
       this.state = state;
    }
   
    public RolehassubmenuId getId() {
        return this.id;
    }
    
    public void setId(RolehassubmenuId id) {
        this.id = id;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public Submenu getSubmenu() {
        return this.submenu;
    }
    
    public void setSubmenu(Submenu submenu) {
        this.submenu = submenu;
    }
    public Boolean getState() {
        return this.state;
    }
    
    public void setState(Boolean state) {
        this.state = state;
    }




}


