package Entities;
// Generated Oct 22, 2016 1:21:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Submenu generated by hbm2java
 */
public class Submenu  implements java.io.Serializable {


     private Integer idsubmenu;
     private Menu menu;
     private String submenu;
     private String pageurl;
     private boolean state;
     private Set<Rolehassubmenu> rolehassubmenus = new HashSet<Rolehassubmenu>(0);

    public Submenu() {
    }

	
    public Submenu(Menu menu, String submenu, boolean state) {
        this.menu = menu;
        this.submenu = submenu;
        this.state = state;
    }
    public Submenu(Menu menu, String submenu, String pageurl, boolean state, Set<Rolehassubmenu> rolehassubmenus) {
       this.menu = menu;
       this.submenu = submenu;
       this.pageurl = pageurl;
       this.state = state;
       this.rolehassubmenus = rolehassubmenus;
    }
   
    public Integer getIdsubmenu() {
        return this.idsubmenu;
    }
    
    public void setIdsubmenu(Integer idsubmenu) {
        this.idsubmenu = idsubmenu;
    }
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }
    public String getSubmenu() {
        return this.submenu;
    }
    
    public void setSubmenu(String submenu) {
        this.submenu = submenu;
    }
    public String getPageurl() {
        return this.pageurl;
    }
    
    public void setPageurl(String pageurl) {
        this.pageurl = pageurl;
    }
    public boolean isState() {
        return this.state;
    }
    
    public void setState(boolean state) {
        this.state = state;
    }
    public Set<Rolehassubmenu> getRolehassubmenus() {
        return this.rolehassubmenus;
    }
    
    public void setRolehassubmenus(Set<Rolehassubmenu> rolehassubmenus) {
        this.rolehassubmenus = rolehassubmenus;
    }




}


