package Entities;
// Generated Sep 27, 2016 8:18:01 PM by Hibernate Tools 4.3.1



/**
 * Wishlist generated by hbm2java
 */
public class Wishlist  implements java.io.Serializable {


     private Integer idWishlist;
     private Application application;
     private Customer customer;

    public Wishlist() {
    }

    public Wishlist(Application application, Customer customer) {
       this.application = application;
       this.customer = customer;
    }
   
    public Integer getIdWishlist() {
        return this.idWishlist;
    }
    
    public void setIdWishlist(Integer idWishlist) {
        this.idWishlist = idWishlist;
    }
    public Application getApplication() {
        return this.application;
    }
    
    public void setApplication(Application application) {
        this.application = application;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }




}


