package Entities;
// Generated Oct 2, 2016 12:23:07 PM by Hibernate Tools 4.3.1



/**
 * Wishlist generated by hbm2java
 */
public class Wishlist  implements java.io.Serializable {


     private WishlistId id;
     private Application application;
     private Customer customer;
     private boolean state;

    public Wishlist() {
    }

    public Wishlist(WishlistId id, Application application, Customer customer, boolean state) {
       this.id = id;
       this.application = application;
       this.customer = customer;
       this.state = state;
    }
   
    public WishlistId getId() {
        return this.id;
    }
    
    public void setId(WishlistId id) {
        this.id = id;
    }
    public Application getApplication() {
        return this.application;
    }
    
    public void setApplication(Application application) {
        this.application = application;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public boolean isState() {
        return this.state;
    }
    
    public void setState(boolean state) {
        this.state = state;
    }




}


